-- 1. Crear bases de datos para cada microservicio
CREATE DATABASE db_usuarios;

-- Sección de creación de tablas e inserción de datos para cada microservicio
-- Usuarios
\c db_usuarios

CREATE TABLE usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    correo VARCHAR(255) UNIQUE NOT NULL,
    direccion VARCHAR(255),
    edad INTEGER NOT NULL CHECK (edad <= 100 AND edad >= 18),
    foto_url VARCHAR(255),
    genero VARCHAR(255) NOT NULL,
    nombre VARCHAR(50) NOT NULL,
    ocupacion VARCHAR(255),
    telefono VARCHAR(255) NOT NULL,
    session_id VARCHAR(255),
    tipo_usuario VARCHAR(100)
);

-- Se eliminó la columna "password" y sus respectivos valores
INSERT INTO usuarios 
(id, correo, direccion, edad, foto_url, genero, nombre, ocupacion, telefono, session_id, tipo_usuario) 
VALUES
(1, 'ma@test.com', 'sucasa', 21, 'https://img.com/foto.jpg', 'Binario', 'Mayckol', 'Estudiante', '1231231', NULL, 'cliente'),
(2, 'ni.bello@duocuc.cl', 'Avenida mirador', 24, 'https://img.com/', 'Masculino', 'Nicolas', 'Estudiante', '1231231', NULL, 'admin'),
(3, 'ro.vargas@duocuc.cl', 'xddd', 27, 'img.com', 'Masculino', 'Rodrigo', 'Estudiante', '123123123', NULL, 'cliente');

-- Actualizamos el contador de IDs para que el próximo usuario registrado sea el ID 4 (basado en el MAX id)
SELECT setval(pg_get_serial_sequence('usuarios', 'id'), (SELECT MAX(id) FROM usuarios));

-- ==========================================
-- Microservicio: Productos
-- ==========================================
CREATE DATABASE db_productos;

\c db_productos

CREATE TABLE productos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    descripcion VARCHAR(500),
    precio NUMERIC(10, 2) NOT NULL,
    stock INTEGER NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMP,
    fecha_actualizacion TIMESTAMP
);

INSERT INTO productos (nombre, descripcion, precio, stock, activo, fecha_creacion, fecha_actualizacion) 
VALUES
('Laptop Pro M2', 'Laptop de alto rendimiento para desarrolladores', 1250.50, 15, true, NOW(), NOW()),
('Teclado Mecánico RGB', 'Teclado switch red en español', 85.99, 40, true, NOW(), NOW()),
('Monitor Ultrawide 34"', 'Monitor curvo 144Hz', 450.00, 10, true, NOW(), NOW());

SELECT setval(pg_get_serial_sequence('productos', 'id'), (SELECT MAX(id) FROM productos));